require:
  - rubocop-rspec
  - rubocop-performance

AllCops:
  NewCops: enable
  TargetRubyVersion: 2.7.2

Style/Documentation:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  IgnoredMethods: ['describe', 'context']

RSpec/MessageSpies:
  EnforcedStyle: receive

RSpec/MultipleMemoizedHelpers:
  Max: 10
