# frozen_string_literal: true

require 'bundler/setup'
require 'i18n'
require 'yaml'
require 'date'
require 'haml'
require 'codebreaker'
require 'delegate'
require 'pry-byebug'
require 'rack/session/cookie'
require 'rack-flash'
require_relative 'config/i18n_config'
require_relative 'modules/database_loader'
require_relative 'modules/render_engine'
require_relative 'modules/game_helper'
require_relative 'lib/view_helper'
require_relative 'lib/statistics'
require_relative 'lib/app'
